"$schema" = "https://starship.rs/config-schema.json"
# Inserts a blank line between shell prompts
add_newline = true
# Custom character for the prompt
[character]
success_symbol = '[>](bold blue)'
error_symbol = '[>](bold red)'

[aws]
disabled = true

[gcloud]
disabled = true
